apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-config
  namespace: paperless
data:
  paperless_redis: "redis://redis.paperless.svc.cluster.local:6379"
  paperless_dbhost: "postgres-svc.metal.svc.cluster.local"
